sudo: required
dist: trusty
language: node_js
node_js:
  - '0.10'
install:
  # Disable the spinner, it looks bad on Travis
  - npm config set spin false
before_script:
  - npm install
script: npm run travis
